dist: trusty
language: ruby
rvm:
  - 2.4.0
services:
  - postgresql
before_install:
    - nvm install 7.3.0
    - nvm use 7.3.0
install:
  - npm install
  - bundle install
before_script:
    - psql -c 'create database buildmycrate_test;' -U postgres
