development:
  adapter: postgresql
  database: buildmycrate_development
  pool: 5
  host: localhost
  username: postgres
  password: postgres

test: &test
  adapter: postgresql
  database: buildmycrate_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: buildmycrate_production
  pool: 5
